"""Order-related constants for Centurion."""

TRADE_TYPE_BID = "bid"
TRADE_TYPE_ASK = "ask"

VALID_TRADE_TYPE = {
    TRADE_TYPE_BID,
    TRADE_TYPE_ASK,
}

TIME_IN_FORCE_FILL_OR_KILL = "fill_or_kill"
TIME_IN_FORCE_GOOD_TILL_CANCELED = "good_till_canceled"
TIME_IN_FORCE_IMMEDIATE_OR_CANCEL = "immediate_or_cancel"

VALID_TIME_IN_FORCE = {
    TIME_IN_FORCE_FILL_OR_KILL,
    TIME_IN_FORCE_GOOD_TILL_CANCELED,
    TIME_IN_FORCE_IMMEDIATE_OR_CANCEL,
}

DEFAULT_TIME_IN_FORCE = TIME_IN_FORCE_FILL_OR_KILL

SELF_TRADE_PREVENTION_TAKER_AT_CROSS = "taker_at_cross"
SELF_TRADE_PREVENTION_MAKER = "maker"

VALID_SELF_TRADE_PREVENTION_TYPE = {
    SELF_TRADE_PREVENTION_TAKER_AT_CROSS,
    SELF_TRADE_PREVENTION_MAKER,
}

DEFAULT_SELF_TRADE_PREVENTION_TYPE = SELF_TRADE_PREVENTION_TAKER_AT_CROSS
